package com.jlu.medicine.mapper;

import com.jlu.medicine.entry.TPerson;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.jdbc.SQL;


public class TPersonSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    public String insertSelective(TPerson record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("person");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TPerson record) {
        SQL sql = new SQL();
        sql.UPDATE("person");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

}