package com.jlu.medicine.mapper;

import com.jlu.medicine.entry.TPerson;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

@Mapper
@Component(value = "userMapper")
public interface TPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    @Delete({
        "delete from person",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    @Insert({
        "insert into person (id, name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     *
     */
    @InsertProvider(type=TPersonSqlProvider.class, method="insertSelective")
    int insertSelective(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     *
     */
    @Select({
        "select",
        "id, name",
        "from person",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR)
    })
     TPerson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPersonSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated
     */
    @Update({
        "update person",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPerson record);
}